### ISSUE TITLE
How can I easily import a lot of data?

### ISSUE THREAD

**Issue by OPEN1004MIND** [FlorianWoelki/obsidian-better-recall#3]
Thank you for creating such a useful plugin.
There is one feature I would like to see added.
It seems like the only way to enter is word by word, but I wish there was a way to enter large data with FRONT and BACK delimiters.
DATA is saved as data.json, which makes it difficult to work in large data.
I wish there was a way to easily save it to a TEXT file or enter a large data.
Thank you.

**Comment by FlorianWoelki** [comment]
Thank you for the suggestion. At the moment (if I am not mistaken), Obsidian sync only syncs the `data.json` file for the specific plugin. That's why I've decided to only save the data inside the `data.json` file.

However, I do have an open issue #2 which describes a solution for saving the data inside a markdown file. This would possibly also solve your issue?

**Comment by OPEN1004MIND** [comment]
Thank you for your quick response.

https://github.com/st3v3nmw/obsidian-spaced-repetition

The above plugin loads an external MD file and supports Word Card.
It's a shame to find all MDs for all Obsidian (I'm worried about speed) 
In the next version, it would be nice if you could set it to read only MDs from the target directory.

**Comment by FlorianWoelki** [comment]
Interesting. I'll try to think of something to have a Markdown file per deck, maybe? There are a lot of things to define, like the actual syntax, how it should be saved, etc. I'll close this issue for now because I think it replicates #2.
